USE fuel;

SELECT
(SELECT COUNT(*) FROM carburanti_it)AS nr_righe, 
(SELECT COUNT(*) FROM information_schema.columns 
WHERE table_schema = 'fuel' AND table_name = 'carburanti_it') AS nr_colonne; 


DESCRIBE carburanti_it; 


ALTER TABLE carburanti_it
CHANGE ï»¿ANNO ANNO year; 
SHOW COLUMNS FROM carburanti_it WHERE field = 'ANNO';


SELECT
  (SELECT COUNT(ANNO) FROM carburanti_it WHERE ANNO IS NULL) AS n_a, 
  (SELECT COUNT(NOME_PRODOTTO) FROM carburanti_it WHERE NOME_PRODOTTO IS NULL) AS n_np,
  (SELECT COUNT(CODICE_PRODOTTO) FROM carburanti_it WHERE CODICE_PRODOTTO IS NULL) AS n_cp,
  (SELECT COUNT(CODICE_MESE) FROM carburanti_it WHERE CODICE_MESE IS NULL) AS n_cm,
  (SELECT COUNT(NOME_MESE) FROM carburanti_it WHERE NOME_MESE IS NULL) AS n_nm,
  (SELECT COUNT(PREZZO) FROM carburanti_it WHERE PREZZO IS NULL) AS n_p,
  (SELECT COUNT(IVA) FROM carburanti_it WHERE IVA IS NULL) AS n_i,
  (SELECT COUNT(ACCISA) FROM carburanti_it WHERE ACCISA IS NULL) AS n_ac,
  (SELECT COUNT(NETTO) FROM carburanti_it WHERE NETTO IS NULL) AS n_n;
 


SELECT * FROM carburanti_it LIMIT 1; 


SELECT 
	COUNT(DISTINCT ANNO) AS A, 
  COUNT(DISTINCT CODICE_MESE) AS C_M,
  COUNT(DISTINCT NOME_MESE) AS N_M,
  COUNT(DISTINCT CODICE_PRODOTTO) AS C_P,
  COUNT(DISTINCT NOME_PRODOTTO) AS N_P ,
  COUNT(DISTINCT PREZZO) AS P,
  COUNT(DISTINCT IVA) AS I,
  COUNT(DISTINCT ACCISA) AS Ac,
  COUNT(DISTINCT NETTO) AS N
FROM carburanti_it; 


SELECT DISTINCT CODICE_MESE, NOME_MESE
FROM carburanti_it; 

ALTER TABLE carburanti_it
DROP COLUMN NOME_MESE; 

DELETE FROM carburanti_it
WHERE CODICE_MESE BETWEEN 13 AND 17;

SELECT COUNT(DISTINCT CODICE_MESE) FROM carburanti_it;

SELECT DISTINCT CODICE_PRODOTTO, NOME_PRODOTTO
FROM carburanti_it; 

ALTER TABLE carburanti_it
DROP COLUMN CODICE_PRODOTTO; 

SELECT DISTINCT ANNO FROM carburanti_it;

DELETE FROM carburanti_it
WHERE (ANNO BETWEEN 1996 AND 2002) OR ANNO = 2023; 


CREATE TABLE Fuel_Price_It AS(
  SELECT 
		ANNO AS anno, 
  	CODICE_MESE AS mese, 
  	NOME_PRODOTTO AS prodotto, 
  	TRUNCATE((PREZZO / 1000), 3) AS prezzo,
 		TRUNCATE((IVA / 1000) + (ACCISA / 1000), 3)AS tax,
  	TRUNCATE((NETTO / 1000),3) AS netto,
  	TRUNCATE((PREZZO - NETTO)/PREZZO, 2) AS inc_tax
	FROM Carburanti_it
	WHERE 
  	NOME_PRODOTTO = "Benzina" 
  	OR NOME_PRODOTTO = "GPL" 
  	OR NOME_PRODOTTO = "Diesel");  
